/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  guideSidebar: [
    {
      type: 'category',
      label: 'Unit Tests',
      link: {type: 'doc', id: 'unit/intro'},
      items: ['unit/setup', 'unit/testing', 'unit/learning-more'],
    },
    {
      type: 'category',
      label: 'Component Tests',
      link: {type: 'doc', id: 'component/intro'},
      items: [
        'component/setup',
        'component/testing',
        'component/effects-and-external-services',
        'component/learning-more',
      ],
    },
    {
      type: 'category',
      label: 'End-to-End Tests',
      link: {type: 'doc', id: 'e2e/intro'},
      items: [
        'e2e/setup',
        'e2e/testing',
        'e2e/external-services',
        'e2e/learning-more',
      ],
    },
    {
      type: 'category',
      label: 'Resources',
      items: [
        'resources/test-pyramid',
        'resources/snapshot-tests',
        'resources/learn-more',
      ],
    },
  ],
};

module.exports = sidebars;
